language: generic
cache:
  directories:
  - $HOME/docker
  - /var/lib/docker/volumes
addons:
  apt:
    packages:
    - libgmp-dev
services:
- docker
# Caching docker images from:
# https://github.com/travis-ci/travis-ci/issues/5358
before_cache:
- mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip --fast > $HOME/docker/$1.tar.gz'
before_install:
- if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
- docker build --cache-from gompiler -t gompiler .
- docker volume create stack
script:
- cd $TRAVIS_BUILD_DIR
- docker run -v stack:/root/.stack gompiler
notifications:
  email: false
  slack:
    rooms:
      secure: Q7uSBbKi43wxqJzADvn8Yk8eHeivyGjAaYL/+spBiXIyGYS16ONz70EeCVtpM5Jvthbc3nyGO5iQJOUSPAIo/lnBQFgdTTZVO/m8BrRSrgPN7wg+qPgUAYu6LqC8Y9FJoDaWWsYrsSLFArPQ+J7WxaQMsI/S+6lIBAlnyyVfarSjf6oeOrd1Q9cSJz2NeNH7XsC3/NYEd9oHPw8RySqWIB0ofJlcLUO8bdkAtJkh8mfbZN82Bwqt8cIJ1ec3Yu5o258BOiQ6omAJYjoZ7s2faPz/Gl+gTec2fUTMRfZOoAF/DVZFyICZZlIY+0n6dMldh05xQOKsGc73WqrrDUCL8ESM0gJpR4lu9wienb2Y+kWeNtCIi0topicXlLLgqHniPFQWAIMChNqSbvJWj23pUxmwxHWM/RLBhf604geZkmWC1+FPxThPsqfLQ1U3GSU6VsLKNH3/JHoZTBDNoDA20mnSNkKWwLRWugauZIulMqqgt2VxiqSNFAFC2Z8TxevE1l962bFKa1jaYDv8svWN2zZcX9nNlqt52hT9rXwphMKQ9NIV9FO+QCb9nPSiybSuKZjYI4AU7fmEvz+7KASEHwBX3EjgKaeshR3gBZJdBzYPph0xgi7N1SNGS5DCQSeevqJnmp+DzNU+ppicEeqNvYSGtTsjvD/3vmXbnlPECCg=
    template:
    - "GLC <%{build_url}|#%{build_number}> by %{author} %{result} in %{duration}"
    - "%{repository_slug}@%{branch} (<%{compare_url}|%{commit}>)"
