language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
branches:
    except:
    - benchmarks
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- cd src && stack --no-terminal --install-ghc test --only-dependencies --pedantic
script:
- cd $TRAVIS_BUILD_DIR
- chmod +x ./travis_test.sh
- ./travis_test.sh
notifications:
  email: false
  slack:
    rooms:
      secure: Q7uSBbKi43wxqJzADvn8Yk8eHeivyGjAaYL/+spBiXIyGYS16ONz70EeCVtpM5Jvthbc3nyGO5iQJOUSPAIo/lnBQFgdTTZVO/m8BrRSrgPN7wg+qPgUAYu6LqC8Y9FJoDaWWsYrsSLFArPQ+J7WxaQMsI/S+6lIBAlnyyVfarSjf6oeOrd1Q9cSJz2NeNH7XsC3/NYEd9oHPw8RySqWIB0ofJlcLUO8bdkAtJkh8mfbZN82Bwqt8cIJ1ec3Yu5o258BOiQ6omAJYjoZ7s2faPz/Gl+gTec2fUTMRfZOoAF/DVZFyICZZlIY+0n6dMldh05xQOKsGc73WqrrDUCL8ESM0gJpR4lu9wienb2Y+kWeNtCIi0topicXlLLgqHniPFQWAIMChNqSbvJWj23pUxmwxHWM/RLBhf604geZkmWC1+FPxThPsqfLQ1U3GSU6VsLKNH3/JHoZTBDNoDA20mnSNkKWwLRWugauZIulMqqgt2VxiqSNFAFC2Z8TxevE1l962bFKa1jaYDv8svWN2zZcX9nNlqt52hT9rXwphMKQ9NIV9FO+QCb9nPSiybSuKZjYI4AU7fmEvz+7KASEHwBX3EjgKaeshR3gBZJdBzYPph0xgi7N1SNGS5DCQSeevqJnmp+DzNU+ppicEeqNvYSGtTsjvD/3vmXbnlPECCg=
    template:
    - "GLC <%{build_url}|#%{build_number}> by %{author} %{result} in %{duration}"
    - "%{repository_slug}@%{branch} (<%{compare_url}|%{commit}>)"
