name:                glc
version:             0.1.0.0
github:              "githubuser/glc"
license:             BSD3
author:              "Gompiler contributors"
#maintainer:          "example@example.com"
copyright:           "2019 Gompiler contributors"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/glc#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- array
- megaparsec
- parser-combinators
- hashtables
- containers
- hspec
- text
- neat-interpolation

library:
  source-dirs: [src, src/generated]

executables:
  glc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glc

tests:
  glc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glc
